print(f"Hello, Would you like to hear a story about a farmdog?")
print(f"Before we get started, I have a few questions for you.")
print(f"After typing your answer, please press the enter key.")
input(f"/nPress the enter  key to continue...")
breed = input("\What breed is your favorite dog:  ")
dogName = input("What is your favorite dog's name:  ")
city = input("What major city do you live nearby:  ")
pond = input("What is your favorite swimming hole:  ")
number = input("What is your favorite number?  ")
print(f"\nLET'S GO!!!!!")
print(f"\nOnce upon a time there was a {breed} farmdog that was named {dogName}.  ")
print(f"{dogName} was rounding up the sheep before he leaves for {city}.  ")
print(f"{dogName} loves to swim, and he feels like today he may have have the chance.  ")
print(f"{dogName} turns toward the pond and runs as fast and as hard as he can.  ")
print(f"While running as fast as he can, {dogName} finally arrives at {pond}. Before jumping in though, he begin's to think.  ")
jumpIntoPond = input(f"\nShould {dogName} jump into {pond}? Type yes or no:  ")
if jumpIntoPond == "yes":
    print(f"\n{dogName} jumps into {pond} splashing and having a great time!  ")
    print(f"When the coyotes notice {dogName} playing and paying no attention to his flock of sheep.  ")
    print(f"They creep in slowly as to not arouse suspicion.  ")
    print(f"Oblivious to the approaching danger, {dogName} gets out of the water accidently falling asleep.  ")
    print(f"{dogName} falls into a deep sleep as the coyote gets closer andd closer.  ")
    print(f"Luckily {dogName} opens his eyes with no time to spare, narrowly escaping unharmed.  ")
else:
    print(f"\n{dogName} decides that it's just to risky to play in the water with hidden danger around every corner.  ")
    print(f"Being a responsible {breed}. {dogName} decides to do a quick scan of the area, when he spots movement in the bushes.  ")
    print(f"Knowing he has {number} sheep to protect. {dogName} slowly begins moving toward the bushes.  ")
    print(f"A mouse!! {dogName} felt relieved to see a little harmless mouse just searching for food.  ")
attackTheCoyote = input(f"\nShould {dogName} attack the coyote approaching his flock? Type yes or no:  ")
while attackTheCoyote.lower() != "yes" and attackTheCoyote.lower() != "no":
    attackTheCoyote = input(f"Please type yes or no:  ")
if attackTheCoyote == "yes":
    print(f"\n{dogName} locks onto the coyote with his eyes, knowing his only job is to protect the {number} sheep in his flock.  ")
    print(f"{dogName} uses the tall grass for coverage as he sneaks closer and closer.  ")
    print(f"{dogName} isn't scared at all, all of his sences hightened.  ")
    print(f"{dogName} pounces on his target, swiftly and powerfully neutralizing the danger.  ")
else:
    print(f"\n{dogName} decided to keep his distance, exactly {number} inches away.  ")
    print(f"Being a cautious {breed} dog, {dogName} uses the tall grass for camoflauge.  ")
    print(f"{dogName} doesnt attack, but he does makes sure the coyotes keeps a safe distance away from his flock.  ")
    